// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCno78V_EEx0Le6PiZUx7OSMWSrBQrOmII',
    appId: '1:958051631664:web:f149989c1149c4f06623f5',
    messagingSenderId: '958051631664',
    projectId: 'app-icy',
    authDomain: 'app-icy.firebaseapp.com',
    databaseURL: 'https://app-icy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-icy.appspot.com',
    measurementId: 'G-KX5CE0FHPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKu0kVqXOiQf7ANkV4rlDpOfMgUCKQzE',
    appId: '1:958051631664:android:9e5451e5c5bc00dc6623f5',
    messagingSenderId: '958051631664',
    projectId: 'app-icy',
    databaseURL: 'https://app-icy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-icy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGgTST8O3vR42jG8WvKAZ7uTcWOkBUMpo',
    appId: '1:958051631664:ios:9dc94b8c2421c3236623f5',
    messagingSenderId: '958051631664',
    projectId: 'app-icy',
    databaseURL: 'https://app-icy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-icy.appspot.com',
    iosClientId: '958051631664-50rvsvb6899knc1p45uftfei54ekoq1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIcy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGgTST8O3vR42jG8WvKAZ7uTcWOkBUMpo',
    appId: '1:958051631664:ios:9dc94b8c2421c3236623f5',
    messagingSenderId: '958051631664',
    projectId: 'app-icy',
    databaseURL: 'https://app-icy-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'app-icy.appspot.com',
    iosClientId: '958051631664-50rvsvb6899knc1p45uftfei54ekoq1v.apps.googleusercontent.com',
    iosBundleId: 'com.example.appIcy',
  );
}
